version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - AUTHENTICATION_DATABASE=strapi
    volumes:
      - ./app:/srv/app
    depends_on:
      - db
    networks:
      - webnet

  db:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    volumes:
      - ./db:/data/db
    restart: always
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app/nginx:etc/nginx/conf.d
      - ./app:/usr/share/nginx/html
    depends_on:
      - strapi
    networks:
      - webnet

networks:
  webnet:
